application: twilio-channel
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /.*
  script: main.app

inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest
